"""Gemma 4 tool-calling orchestrator for reef analysis and recommendations."""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Literal

import requests
from pydantic import BaseModel, Field, ValidationError

try:
    from .environmental_stress import calculate_environmental_stress
    from .gemma_prompt import SYSTEM_PROMPT, build_analysis_prompt
    from .intervention_simulation import build_intervention_options
    from .predict_risk import predict_14_day_bleaching_risk
    from .restoration_knowledge_base import RESTORATION_TECHNIQUES
    from .roi_calculator import calculate_restoration_roi
    from .tool_schemas import TOOLS
except ImportError:  # Support direct execution from backend/.
    from environmental_stress import calculate_environmental_stress
    from gemma_prompt import SYSTEM_PROMPT, build_analysis_prompt
    from intervention_simulation import build_intervention_options
    from predict_risk import predict_14_day_bleaching_risk
    from restoration_knowledge_base import RESTORATION_TECHNIQUES
    from roi_calculator import calculate_restoration_roi
    from tool_schemas import TOOLS


LOGGER = logging.getLogger(__name__)
DEFAULT_OLLAMA_HOST = "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = "gemma4"


class GemmaUnavailableError(RuntimeError):
    """Raised when Ollama or the configured Gemma 4 model is unavailable."""


class GemmaResponseError(RuntimeError):
    """Raised when Gemma 4 returns an invalid recommendation."""


TechniqueId = Literal[
    "temporary_shading",
    "coral_gardening",
    "access_limit",
    "microfragmenting",
    "substrate_stabilization",
    "heat_resistant_outplanting",
    "larval_propagation",
    "no_intervention_monitoring",
]


class GemmaInterventionNarrative(BaseModel):
    technique_id: TechniqueId
    rationale: str = Field(min_length=1, max_length=1600)
    implementation_steps: list[str] = Field(min_length=3, max_length=6)
    caveats: list[str] = Field(min_length=1, max_length=6)


class GemmaRecommendation(BaseModel):
    """Frontend-compatible structured recommendation generated by Gemma 4."""

    alert_level: Literal["LOW", "MODERATE", "HIGH", "CRITICAL"]
    coral_health_summary: str = Field(min_length=1, max_length=600)
    environmental_assessment: str = Field(min_length=1, max_length=1000)
    recommended_technique: TechniqueId
    technique_name: str = Field(min_length=1, max_length=300)
    reasoning: str = Field(min_length=1, max_length=3000)
    predicted_survival_rate: str = Field(min_length=1, max_length=30)
    estimated_cost_per_hectare: str = Field(min_length=1, max_length=50)
    risk_factors: list[str] = Field(min_length=1, max_length=12)
    next_steps: list[str] = Field(min_length=1, max_length=12)
    confidence_score: float = Field(ge=0.0, le=1.0)
    interventions: list[GemmaInterventionNarrative] = Field(
        min_length=3,
        max_length=5,
    )


OLLAMA_RECOMMENDATION_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "alert_level": {
            "type": "string",
            "enum": ["LOW", "MODERATE", "HIGH", "CRITICAL"],
        },
        "coral_health_summary": {"type": "string"},
        "environmental_assessment": {"type": "string"},
        "recommended_technique": {
            "type": "string",
            "enum": [
                "coral_gardening",
                "temporary_shading",
                "access_limit",
                "microfragmenting",
                "substrate_stabilization",
                "heat_resistant_outplanting",
                "larval_propagation",
                "no_intervention_monitoring",
            ],
        },
        "technique_name": {"type": "string"},
        "reasoning": {"type": "string"},
        "predicted_survival_rate": {"type": "string"},
        "estimated_cost_per_hectare": {"type": "string"},
        "risk_factors": {
            "type": "array",
            "items": {"type": "string"},
        },
        "next_steps": {
            "type": "array",
            "items": {"type": "string"},
        },
        "confidence_score": {"type": "number"},
        "interventions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "technique_id": {
                        "type": "string",
                        "enum": [
                            "temporary_shading",
                            "coral_gardening",
                            "access_limit",
                            "microfragmenting",
                            "substrate_stabilization",
                            "heat_resistant_outplanting",
                            "larval_propagation",
                            "no_intervention_monitoring",
                        ],
                    },
                    "rationale": {"type": "string"},
                    "implementation_steps": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "caveats": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
                "required": [
                    "technique_id",
                    "rationale",
                    "implementation_steps",
                    "caveats",
                ],
            },
        },
    },
    "required": [
        "alert_level",
        "coral_health_summary",
        "environmental_assessment",
        "recommended_technique",
        "technique_name",
        "reasoning",
        "predicted_survival_rate",
        "estimated_cost_per_hectare",
        "risk_factors",
        "next_steps",
        "confidence_score",
        "interventions",
    ],
}


TOOL_FUNCTIONS = {
    "calculate_restoration_roi": calculate_restoration_roi,
    "calculate_environmental_stress": calculate_environmental_stress,
    "predict_14_day_bleaching_risk": predict_14_day_bleaching_risk,
}


def _ollama_host() -> str:
    return os.getenv("REEFGUARDIAN_OLLAMA_HOST", DEFAULT_OLLAMA_HOST).rstrip("/")


def _ollama_model() -> str:
    return os.getenv("REEFGUARDIAN_OLLAMA_MODEL", DEFAULT_OLLAMA_MODEL).strip()


def _ollama_chat(payload: dict[str, Any]) -> dict[str, Any]:
    timeout_seconds = float(os.getenv("REEFGUARDIAN_OLLAMA_TIMEOUT_SECONDS", "150"))
    try:
        response = requests.post(
            f"{_ollama_host()}/api/chat",
            json=payload,
            timeout=(3.0, timeout_seconds),
        )
    except requests.ConnectionError as exc:
        raise GemmaUnavailableError(
            f"Ollama is not reachable at {_ollama_host()}. "
            "Install/start Ollama and pull the configured Gemma 4 model."
        ) from exc
    except requests.Timeout as exc:
        raise GemmaUnavailableError(
            f"Gemma 4 exceeded the {timeout_seconds:g}-second Ollama timeout."
        ) from exc

    if response.status_code >= 400:
        try:
            detail = response.json().get("error", response.text)
        except ValueError:
            detail = response.text
        if response.status_code == 404:
            detail = (
                f"{detail} Pull it with: ollama pull {_ollama_model()}"
            )
        raise GemmaUnavailableError(
            f"Ollama returned HTTP {response.status_code}: {detail}"
        )

    try:
        result = response.json()
    except ValueError as exc:
        raise GemmaResponseError("Ollama returned a non-JSON response.") from exc
    if not isinstance(result.get("message"), dict):
        raise GemmaResponseError("Ollama response did not contain a chat message.")
    return result


def _tool_arguments(tool_call: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    function = tool_call.get("function") or {}
    name = str(function.get("name") or "")
    arguments = function.get("arguments") or {}
    if isinstance(arguments, str):
        try:
            arguments = json.loads(arguments)
        except json.JSONDecodeError as exc:
            raise GemmaResponseError(
                f"Gemma 4 returned invalid arguments for tool {name!r}."
            ) from exc
    if not isinstance(arguments, dict):
        raise GemmaResponseError(
            f"Gemma 4 returned non-object arguments for tool {name!r}."
        )
    return name, arguments


def _execute_tool(tool_call: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    name, arguments = _tool_arguments(tool_call)
    function = TOOL_FUNCTIONS.get(name)
    if function is None:
        return name, {"error": f"Unknown or disallowed tool: {name}"}
    try:
        result = function(**arguments)
        return name, result if isinstance(result, dict) else {"result": result}
    except (TypeError, ValueError) as exc:
        return name, {"error": str(exc)}
    except Exception:
        LOGGER.exception("Gemma 4 tool %s failed", name)
        return name, {"error": f"{name} failed during execution"}


def call_gemma_with_tools(prompt: str, max_iterations: int = 4) -> str:
    """Run a bounded Gemma 4 tool loop and request a schema-constrained result."""

    messages: list[dict[str, Any]] = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": prompt},
    ]
    model = _ollama_model()

    tool_cache: dict[str, tuple[str, dict[str, Any]]] = {}
    for _ in range(max_iterations):
        response = _ollama_chat(
            {
                "model": model,
                "messages": messages,
                "tools": TOOLS,
                "stream": False,
                "think": "low",
                "options": {
                    "temperature": 0.1,
                    "num_ctx": 8192,
                    "num_predict": 1400,
                },
            }
        )
        message = response["message"]
        messages.append(message)
        tool_calls = message.get("tool_calls") or []
        if not tool_calls:
            break

        for tool_call in tool_calls:
            tool_name, arguments = _tool_arguments(tool_call)
            signature = json.dumps(
                {"name": tool_name, "arguments": arguments},
                sort_keys=True,
                default=str,
            )
            if signature in tool_cache:
                tool_name, tool_result = tool_cache[signature]
            else:
                tool_name, tool_result = _execute_tool(tool_call)
                tool_cache[signature] = (tool_name, tool_result)
            messages.append(
                {
                    "role": "tool",
                    "tool_name": tool_name,
                    "content": json.dumps(tool_result, default=str),
                }
            )
    messages.append(
        {
            "role": "user",
            "content": (
                "Tool collection is now complete. Using the evidence above, "
                "return the final recommendation. "
                "Follow the supplied JSON schema exactly and include 3 to 5 "
                "distinct, detailed intervention options ranked best first. "
                "Each option needs at least 3 implementation steps. Do not call "
                "more tools."
            ),
        }
    )
    final_response = _ollama_chat(
        {
            "model": model,
            "messages": messages,
            # Ollama's grammar parser accepts a smaller JSON-Schema subset than
            # Pydantic emits. Full length/range validation still happens below.
            "format": OLLAMA_RECOMMENDATION_SCHEMA,
            "stream": False,
            "think": False,
            "options": {
                "temperature": 0,
                "num_ctx": 8192,
                "num_predict": 1400,
            },
        }
    )
    return str(final_response["message"].get("content") or "")


def parse_gemma_response(response_text: str) -> dict[str, Any]:
    """Validate Gemma 4 output against the public recommendation contract."""

    try:
        recommendation = GemmaRecommendation.model_validate_json(response_text)
    except ValidationError as exc:
        raise GemmaResponseError(
            f"Gemma 4 returned an invalid recommendation: {exc}"
        ) from exc
    return recommendation.model_dump()


def _ground_recommendation(
    recommendation: dict[str, Any],
    cv_output: dict[str, Any],
    sensor_data: dict[str, Any],
    location_name: str,
) -> dict[str, Any]:
    """Replace budget/survival claims with deterministic tool calculations."""

    stress = calculate_environmental_stress(
        water_temp_c=float(sensor_data["water_temp_c"]),
        ph_level=float(sensor_data["ph_level"]),
        turbidity_ntu=float(sensor_data["turbidity_ntu"]),
        salinity_ppt=float(sensor_data["salinity_ppt"]),
    )
    gemma_options = list(recommendation.pop("interventions", []))
    primary_id = recommendation["recommended_technique"]
    if all(option.get("technique_id") != primary_id for option in gemma_options):
        gemma_options.insert(
            0,
            {
                "technique_id": primary_id,
                "rationale": recommendation["reasoning"],
                "implementation_steps": recommendation["next_steps"],
                "caveats": recommendation["risk_factors"],
            },
        )

    required_prediction_inputs = (
        "latitude",
        "longitude",
        "depth_m",
        "sst_kelvin",
        "dhw",
    )
    if all(sensor_data.get(field) is not None for field in required_prediction_inputs):
        risk = predict_14_day_bleaching_risk(
            latitude=float(sensor_data["latitude"]),
            longitude=float(sensor_data["longitude"]),
            depth=float(sensor_data["depth_m"]),
            sst_kelvin=float(sensor_data["sst_kelvin"]),
            dhw=float(sensor_data["dhw"]),
            coral_health=str(cv_output.get("health", "unknown")),
        )
        baseline_risk = float(risk["bleaching_risk_score"])
    else:
        baseline_risk = float(stress["stress_score"])

    interventions = build_intervention_options(
        cv_output=cv_output,
        sensor_data=sensor_data,
        location_name=location_name,
        baseline_risk_score=baseline_risk,
        gemma_options=gemma_options,
        limit=4,
    )
    primary = interventions[0]
    return {
        **recommendation,
        "recommended_technique": primary["technique_id"],
        "technique_name": primary["name"],
        "predicted_survival_rate": primary["predicted_survival_rate"],
        "estimated_cost_per_hectare": primary["cost_per_hectare"],
        "baseline_risk_score": round(baseline_risk),
        "interventions": interventions,
        "model": _ollama_model(),
    }


def get_gemma_status() -> dict[str, Any]:
    """Report Ollama reachability and whether the configured model is installed."""

    model = _ollama_model()
    try:
        response = requests.get(f"{_ollama_host()}/api/tags", timeout=(2.0, 4.0))
        response.raise_for_status()
        installed_names = [
            str(item.get("name") or item.get("model") or "")
            for item in response.json().get("models", [])
        ]
    except (requests.RequestException, ValueError):
        return {
            "status": "unavailable",
            "ollama_host": _ollama_host(),
            "model": model,
            "installed": False,
        }

    requested_base = model.split(":", 1)[0]
    installed = any(
        name == model
        or (
            ":" not in model
            and name.split(":", 1)[0] == requested_base
        )
        for name in installed_names
    )
    return {
        "status": "ready" if installed else "model_missing",
        "ollama_host": _ollama_host(),
        "model": model,
        "installed": installed,
    }


def analyze_reef(
    cv_output: dict[str, Any],
    sensor_data: dict[str, Any],
    location_name: str,
) -> dict[str, Any]:
    """Analyze reef evidence with Gemma 4 and return a grounded recommendation."""

    try:
        prompt = build_analysis_prompt(cv_output, sensor_data, location_name)
        response_text = call_gemma_with_tools(prompt)
        recommendation = parse_gemma_response(response_text)
        return _ground_recommendation(
            recommendation,
            cv_output,
            sensor_data,
            location_name,
        )
    except (GemmaUnavailableError, GemmaResponseError, KeyError, ValueError) as exc:
        LOGGER.warning("Gemma 4 analysis unavailable: %s", exc)
        return {
            "alert_level": "ERROR",
            "reasoning": str(exc),
            "model": _ollama_model(),
        }


GEMMA_ORCHESTRATOR = analyze_reef


if __name__ == "__main__":
    print(json.dumps(get_gemma_status(), indent=2))
